version: "3"

services:
  web:
    build: .
    volumes:
      - ./db:/app/db
    environment:
      - FW_ENDPOINTS=https://api.mycity.it/apiaperte/aws/sns/handle
      - FW_ENDPOINT_TOKENS=e06f1d5a-a835-4364-ade3-1c9feff062c1
      - ACCESS_TOKENS=4d15186f-ee60-45eb-8d64-403e164d5812
      - ACCESS_TOKENS_ALIASES=aws-sns
    ports:
      - "9080:3000"
