version: "3"

services:
  web:
    build: .
    volumes:
      - ./access.log:/app/access.log
    environment:
      - FW_ENDPOINTS=https://api.mycity.it/apiaperte/aws/sns/handle
      - FW_ENDPOINT_TOKENS=e06f1d5a-a835-4364-ade3-1c9feff062c1
      - ACCESS_TOKEN=4d15186f-ee60-45eb-8d64-403e164d5812
    ports:
      - "1234:3000"
